### PR TITLE
use sciml versions of packages

### PR DESCRIPTION
**Pull request by Datseris**
Closes https://github.com/JuliaDynamics/DynamicalSystems.jl/issues/163

### CODE REVIEW

**Comment by awage** [comment]
I think I understand what is going on. The check fails because it is expecting the merged version of `Chaostools` that is not yet in the Julia repository.

**Comment by awage** [comment]
I messed up with the master. It is not what I though. I revert this commit with another PR.

**Comment by awage** [comment]
@Datseris  I have been checking the tag versions and I added tag v2.1.4 for PR #164. I removed it yesterday after my confusion. 

It is better that you register the package yourself. It reduces the probability of errors!

**Comment by Datseris** [comment]
okay, fair, from now own I am responsible for all package tagging. You are right, this is the safest option because one person needs to keep track of _every_ version for this to work properly.

**Comment by awage** [comment]
The problem is that I never mastered the process from end to end. This is the reason of all this confusion about these PR. I have no problem in helping you with this! I must first understand clearly the version and tagging systems.

**Pull request merged**
