### PR TITLE
Update `interactive_poincaresos` method to v3

### LINKED ISSUE #220: Update interactive_poincaresos to v3
Since interactive_poincaresos is absorbed into DynamicalSystems from julia-1.9, encountering argument errors for 
differential equation keywords

example is taken from [documentation of interactive poincare sections](https://juliadynamics.github.io/DynamicalSystems.jl/dev/visualizations/#Interactive-Poincar%C3%A9-Surface-of-Section)

running the documented script with `using GLMakie, OrdinaryDiffEq, DynamicalSystems` since interactive_poincaresos is in 
InteractiveDynamics package as well.

yields, 

```
 interactive_poincaresos(::Any, ::Any, ::Any, ::Any; direction, tfinal, rootkw, color, scatterkwargs, labels, diffeq) got unsupported keyword arguments "alg", "abstol", "reltol"
   @ DynamicalSystemsVisualizations ~/.julia/packages/DynamicalSystems/cuQyu/ext/src/poincareclick.jl:3
```
the keyword 'diffeq' that was given to interactive_poincaresos  `diffeq = (alg = Vern9(), abstol = 1e-9, reltol = 1e-9)`

system status

```

Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores



Status `~/.julia/environments/v1.9/Manifest.toml`
  [f3fd9213] Attractors v1.12.0
  [608a59af] ChaosTools v3.1.1
  [ab4b797d] ComplexityMeasures v2.8.0
  [5732040d] DelayEmbeddings v2.7.3
  [61744808] DynamicalSystems v3.2.2
  [6e36e845] DynamicalSystemsBase v3.4.1
  [4665ce21] FractalDimensions v1.7.3
  [31e2f376] PredefinedDynamicalSystems v1.2.0
  [639c3291] RecurrenceAnalysis v2.0.5
  [40b095a5] StateSpaceSets v1.4.4
  [c804724b] TimeseriesSurrogates v2.6.2
```

### PR DESCRIPTION
**Pull request by GabrielMajeri**
Closes #220.

I tried to keep the changes to the original code to a minimum.

### CODE REVIEW

**Review by Datseris — COMMENTED** [review]
Good, does this work?

**Comment by Datseris** [comment]
In case you are interested: i was working on a more general function: a general 2D clicker, that does what this Poincare GUI does, but for any "2D" dynamical system. This would work for 2D projected dynamical systems, poincare maps of 3D systems, stroboscopic maps of 2D systems with time forcing, and standard 2D systems (either discrete or continuous).

Would you be interested to do this? In principle it should be too much work from what you have here. You would make a generic function that directly accepts the actual dynamical system (unlike here where the poincare map is generated inside the function).

**Comment by GabrielMajeri** [comment]
> Good, does this work?

Yep, I've tested it locally:

image

> Would you be interested to do this? In principle it shouldn't be too much work from what you have here. You would make a generic function that directly accepts the actual dynamical system (unlike here where the poincare map is generated inside the function).

Sounds interesting, and I might be able to implement it, but I'd appreciate if we could merge this as-is for now and maybe open another issue for this extra improvement. I had to fix this bug for some PhD work and I'd like to get that through first 😅

**Review by Datseris — APPROVED** [review]
Of course, good luck with the PhD! I was working on this library when I was doing mine as well, happy to see that it helps ;)

**Pull request merged**
