### PR TITLE
Revert "use sciml versions of packages"

### PR DESCRIPTION
**Pull request by awage**
Reverts JuliaDynamics/DynamicalSystems.jl#164

### CODE REVIEW

**Comment by awage** [comment]
I am confused. Tests are failing for this PR also. I let you on commands.

**Comment by Datseris** [comment]
@awage I think it is because you didn't actually register a new release, but only tagged one. I register new releases here: juliahub.com

**Comment by awage** [comment]
@Datseris I though you had some magic bot that did the work for you. I only tagged the release. At some point I hit the panic button and waited for the cavalry to arrive!

**Comment by Datseris** [comment]
But I just saw another notification that you released for DynamicalSystems.jl, that was with what "version" and "tagging system"?

**Comment by awage** [comment]
OK, here is the timeline. Just to be sure that we I haven't let slip something on the way: 

* I tagged `ChaosTools.jl` 2.6.2
* I merged #164 into master
* tagged `DynamicalSystems.jl` v2.1.4
* I saw tests were failing on master: deleted tag v2.1.4 and opened #166 
* Got confused since tests in reverted PR were still failing. 
* Yesterday I saw that version was stable and added tag v2.1.4

I am not sure that this tagged version has been merged into the Julia repository.

**Comment by Datseris** [comment]
My central question is, when you say "I tagged X" what does this mean practically? What do you do? You create a tag on GitHub only? Or is there something more that you do when you "tag"?

**Comment by awage** [comment]
Exactly: I tagged the release on GitHub only. My mistake was to believe
that there was a bot that automatically takes the release and merged
everything into the Julia repository.

**Comment by Datseris** [comment]
Okay, so, for future reference, here is how I make releases: (there are other ways as well)

1. Make sure that the version in Project.toml is the correct version I want to release.
2. Go to juliahub.com and login with GitHub account.
3. Click Contributing>Register New Packages
4. Paste https://github.com/JuliaDynamics/RepositoryToBeRegistered.jl and click register.
5. Magic bots take care of everything else, from registering new version on the general registry to tagging a new release on the GitHub repo

But I agree that it is better to have a single "release manager" for a big repo like DynamicalSystems.jl, because with my method of tagging releases only the tagging person gets notifications. So I'll take care of releases from now own, sorry for putting you through all this trouble, I've internalized the release pipeline so much that I have forgotten its intricacies...

**Pull request closed without merging**
