### PR TITLE
Hacky test for JuliaDynamics/ChaosTools.jl#109

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by Datseris** [comment]
It doesn't seem to work for me: https://juliadynamics.github.io/DynamicalSystems.jl/previews/PR109/chaos/nlts/#ChaosTools.numericallyapunov

clicking the "1" doesn't bring me to the citation.

**Comment by asinghvi17** [comment]
Let me try one thing.  I think the spacing may play a role here...

**Comment by Datseris** [comment]
@asinghvi17 This worked now. Unfortuantely we cannot merge this change. Please have a look at the Docs and you will realize why. 

The references go at the bottom of the page with number "1". Now, if you look at the Broomhead king method, it also has a reference of number "1". This is ambiguous, which 1 is the broomhead, which 1 is the Lyapunovs...? And I don't think it is reasonable to start tracking citations in the docs.

**Comment by asinghvi17** [comment]
Makes sense.  Unless we use author names or something as markers, it would get complicated.

**Comment by Datseris** [comment]
What we *could* do, is modify all docstrings to have different code names instead of numbers (e.g. LastName-Date, e.g. `Lyapunov1902`, `Pecora2007`, etc.). Does the citations that go to the end of the page work with this kind of syntax as well?

What happens when one has the same code word across different docstrings? Can you check this?

**Comment by Datseris** [comment]
Does the same syntax work with codeworrds instead of numbers @asinghvi17  ? If it does, then that is the solution.

**Comment by Datseris** [comment]
Seems to work, right?!

**Comment by asinghvi17** [comment]
Yes, it seems to work!  Beware that you can only use 1 line for the footnote, though, and you may want to omit the `## References` headers from the docstring.

**Pull request closed without merging**
