### PR TITLE
docs and examples for pecuzal_embedding

### PR DESCRIPTION
**Pull request by hkraemer**
Since I can not see the immediate results I am not quite sure if the examples work, because I do not know if there is an own scope for each individual code block or not. If that is the case, I would need to squeeze the three example-code-blocks into a single one and use in-code comments for the "story". Hopefully that is not the case.

### CODE REVIEW

**Comment by Datseris** [comment]
To see the docs you have 2 options:

1. Locally run `docs/make.jl`
2. Wait for the Travis build to finish. Test docs will them be uploaded to https://juliadynamics.github.io/DynamicalSystems.jl/previews/PR117 

I'll have a look when the docs build and see if any adjustments are necessary. I can tell you already that you can't use `print` statements, but instead show the things you want to print as the final statement of the code block.

**Comment by hkraemer** [comment]
Thanks!

> I'll have a look when the docs build and see if any adjustments are necessary. I can tell you already that you can't use print statements, but instead show the things you want to print as the final statement of the code block.

As far as I can see, the println-statements do work. I leave it for now.

In the `pecuzal_embedding`-function we use some `println`-statements (happening in the `pecuzal_break_criterion`-auxilary function), like we do it in `optimal_traditional_de`. When I run these function in Atom (Juno 0.3.0, Julia client 0.12.6) sometimes it prints the statements, sometime it does not! This is quite wired. Anyway, when I run the code in the Terminal it always prints the statements. 

Now the strange thing: In the `estimate.md`-docs-file, the code, which runs in the ```@example-code blocks does produce the statements, i.e. prints the `println`-statements from the code (like in my Terminal). But for the very last example I pushed (noise), it does not print the statement, but rather prints the whole vector, even though I did not call that one in the code-example. What is going on here? Any idea?

There is another thing: When I locally run `docs/make.jl` the corresponding `index.html` shows this output under all example-code-blocks, which used PyPlot

sys:1: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
I guess that is something internally and does not matter, hum? Because the online version does not have these statements. 

Still, also my local `index.html` does not print the desired output `println("Algorithm stopped due to increasing L-values. "*
                    "Valid embedding NOT achieved ⨉.“)` for the very last example, but for all other ones it does. Strange things are happening

**Comment by Datseris** [comment]
huh that's weird, for some reason I cannot checkout this pull request locally

**Comment by Datseris** [comment]
Alright, I'm gonna merge this as is and open a new PR that does some improvements, which you can also contribute to

**Pull request merged**
