### PR TITLE
Added warning messages for old docs

### PR DESCRIPTION
**Pull request by ShrutiRDalvi**
Solves #225

### CODE REVIEW

**Comment by Datseris** [comment]
Hello, thanks! As it is impossible to actually review this PR due to the 700+ changed files, could you please tell me what you did? Did you just run these two lines of code referenced in the issue?

**Comment by ShrutiRDalvi** [comment]
yup thats all I did. Is there a way to build the docs locally and see if the warning pops up?

**Comment by Datseris** [comment]
The only way I see is to check-out locally the `gh-branch` and manually open the `index.html` file for any of the older versions. Have you done something like that?

**Comment by Datseris** [comment]
Alright, I checked out the PR locally and I can confirm everything works! Thanks a lot!!!

**Pull request merged**
