### PR TITLE
Update docs with info about period estimation

### PR DESCRIPTION
**Pull request by asinghvi17**
Needs JuliaDynamics/ChaosTools.jl#89

### CODE REVIEW

**Comment by Datseris** [comment]
Or JuliaDynamics/ChaosTools#90

**Comment by asinghvi17** [comment]
Both really :P

**Comment by Datseris** [comment]
@asinghvi17 if you are willing to publicly show your modified FigzHugh system, I think it would be a nice opportunity to use it as an example in the documentation!

**Comment by asinghvi17** [comment]
Yeah, go for it - it'll be published soon (hopefully).

**Pull request merged**
