### PR TITLE
[WIP] Add poincare_explorer.jl

### PR DESCRIPTION
**Pull request by SebastianM-C**

### CODE REVIEW

**Comment by Datseris** [comment]
@SebastianM-C should I merge or do you want to add some documentative comments first"?

**Comment by SebastianM-C** [comment]
I'll add some documentation first.

**Comment by SebastianM-C** [comment]
I added some docs. Let me know if I should add more explanations.
Sorry for the delay.

**Comment by Datseris** [comment]
Awesome Sebastian. Can you do me a favor and just copy paste this file to this repo: https://github.com/JuliaDynamics/InteractiveChaos.jl (i am not doing that to ensure you get the commits attributed to you)

I am moving the interactive applications there, along with their development. There we can open issues and discuss how we want to improve existing functionality and add new one.

**Pull request closed without merging**
